required-players: 2
max-players: 8
lobby-timer: 30
head-start-timer: 60
game-timer: 180
transform-timer: 3
hider-health: 3
lobby-location:
    world: world
    x: 0.5
    y: 64.0
    z: 0.5
    yaw: 0
    pitch: 0